name: build

on: [push, pull_request]

env:
  build-folder: build
  python-version: 3.9

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - name: Windows Clang 13 x86 64 RelWithDebInfo MT
            os: windows-latest
            build_type: RelWithDebInfo
            profile: clang_x86_64_asan

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}

      - name: Install requirements
        run: python -m pip install --upgrade pip conan

      - name: Install dependencies
        run: conan install . -if ${{ env.build-folder }} -b outdated
          -s build_type=${{ matrix.config.build_type }} -pr .profile/${{ matrix.config.profile }}
          -s:b build_type=${{ matrix.config.build_type }} -pr:b .profile/${{ matrix.config.profile }}

      - name: Build
        run: conan build . -bf ${{ env.build-folder }}

      - name: Publish compile_commands.json
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: compile_commands
          path: ${{ env.build-folder }}/compile_commands.json
