name: build

on: [push, pull_request]

env:
  python-version: 3.12

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: aarch64-linux-android [windows]
            os: windows-latest
            build_type: Debug
            profile_host: aarch64-linux-android
            profile_build: x86_64-pc-windows-gnu

          - name: aarch64-linux-android [linux]
            os: ubuntu-latest
            build_type: Debug
            profile_host: aarch64-linux-android
            profile_build: x86_64-unknown-linux-gnu

    env:
      PROFILE_HOST: .conan2/profiles/${{ matrix.config.profile_host }}
      PROFILE_BUILD: .conan2/profiles/${{ matrix.config.profile_build }}
      BUILD_TYPE: ${{ matrix.config.build_type }}
      CONAN_INSTALL_EXTRA_ARGS: --build=missing
      CONAN_BUILD_EXTRA_ARGS: --build=missing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python-version }}

      - uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: 1.12.0

      - name: Install Conan
        run: python -m pip install --upgrade pip conan

      - name: Install dependencies
        run: make deps

      - name: Build
        run: make build
