name: Tests

on: [push, pull_request]

env:
  python-version: 3.9

jobs:
  build:
    name: Windows MSVC 19.29 x86 64 Debug
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}

      - name: Install requirements
        run: python -m pip install --upgrade pip conan

      - name: Build
        shell: bash
        run: ./build.sh
